name: "CI CD Pipeline for Auth Frontend Preprod"

on:
    workflow_dispatch:

jobs:
    cicd: 
        runs-on: ubuntu-latest
        environment: preprod
        
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'

            - name: "Check Node Installation"
              run: | 
                node --version
                npm --version

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: "Install vercel cli"
              run: npm install -g vercel

            - name: "List Directory"
              run: ls

            - name: Run EsLint
              run: npm run lint

            - name: Create Build 
              run: npm run build

            - name: Deploy to Vercel 
              run : vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm --name=auth_preprod
